# Generated by Django 4.2.3 on 2023-07-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('자유', '자유'), ('취미', '취미'), ('팁', '팁')], default='일반', max_length=30),
        ),
    ]
