# Generated by Django 4.2.3 on 2023-07-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('free', '자유'), ('hobby', '취미'), ('tip', '팁')], default='자유', max_length=30),
        ),
    ]
