# Generated by Django 4.2.3 on 2023-07-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('free', '자유'), ('hobby', '취미'), ('info', '정보')], default='자유', max_length=30),
        ),
    ]
