# Generated by Django 4.2.3 on 2023-07-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('자유', '자유'), ('취미', '취미'), ('정보', '정보')], default='자유', max_length=30),
        ),
    ]
